### ISSUE TITLE
autoload- und contao-manager-plugin-Pfad werden nicht mehr korrekt erstellt

### ISSUE THREAD

**Issue by heimseiten** [markocupic/contao-bundle-creator-bundle#10]
Habe es nicht mit einer Contao Neuinstallation probiert, aber der Pfad wurde vorher korrekt erstellt und nun nicht mehr.

![Bildschirmfoto 2021-01-27 um 11 45 35](https://user-images.githubusercontent.com/6552484/105981832-d6cc3480-6096-11eb-8f5b-f984df91304d.png)

**Comment by markocupic** [comment]
Wie sieht es jetzt aus?
Lg Marko

**Comment by heimseiten** [comment]
Leider nein. Mit Version 1.2.28 getestet.

**Comment by markocupic** [comment]
Ok. ;-( Und mit Version 1.2.29

**Comment by heimseiten** [comment]
ja! Vielen Dank!
