### ISSUE TITLE
Generierung ohne Frontend-Modul führt zu Fehler

### ISSUE THREAD

**Issue by koertho** [markocupic/contao-bundle-creator-bundle#11]
Hallo, ich teste gerade dein/euer Bundle. Beim Erstellen mit deaktivierter Frontend-Modul-Erstellung kam dieser Fehler. Wenn ich es aktiviere, läuft es durch.

![image](https://user-images.githubusercontent.com/12064642/107935059-2c527d80-6f81-11eb-9542-c766339ba17e.png)

Bundle: 1.3.7
PHP: 7.4
Contao 4.9.11

**Comment by markocupic** [comment]
Hallo Thomas
Besten Dank für dein Feedback. Ich habe am Wochenende den Code überarbeitet/auf den Kopf gestellt, so dass alle Maker über Subscriber eingebaut werden können. Dadurch wird die Extension auch sehr einfach erweiterbar. 

Du darfst gerne testen und ich freue mich auf euer Feedback.

Liebe Grüsse

Marko

**Comment by koertho** [comment]
@markocupic Sehr schick, lief insgesamt auch sehr gut. Ist ja auch kein Problem, die unnötigen Sachen zu entfernen, ich dachte nur, ich reporte gleiche alles, was mir auffällt :)

**Comment by markocupic** [comment]
@koertho 
Danke für dein Feedback. Bin froh darum. 👍  Ich musste letzten Sommer ca. 20 Contao 3 Erweiterungen updaten. Da kam mir die Idee diesen Maker zu programmieren. Habe dabei auch das eine oder andere gelernt. :-)
Ich hoffe, andere können das Teil auch einsetzen. Die Erweiterung ist noch nicht fertig. 
Als nächsten Maker werde ich mir wohl die Configuration Klasse vornehmen. 

Liebe Grüsse

Marko
