### ISSUE TITLE
neue Einträge in der services.yml seit Symfony 5 nötig

### ISSUE THREAD

**Issue by heimseiten** [markocupic/contao-bundle-creator-bundle#16]
Siehe: https://github.com/terminal42/contao-pageimage/issues/46#issuecomment-825963078

Danke!!!

**Comment by markocupic** [comment]
@heimseiten 
Fixed in https://github.com/markocupic/contao-bundle-creator-bundle/commit/2c8c84f850efd407480fa4d9a0fd5cb14bb076fa

Please try version 1.4.1

**Comment by heimseiten** [comment]
Danke. Wenn ich jetzt ein Testmodul erzeuge und installiere, wird das Backend nicht mehr aufgerufen und folgendes angezeigt:

Attempted to load class "TestModuleController" from the global namespace. Did you forget a "use" statement for "Heimseiten\ContaoTestBundle\Controller\FrontendModule\TestModuleController"?

**Comment by markocupic** [comment]
Hallo Niels
Ich kann den Fehler nicht reproduzieren. 
Getestet unter Contao 4.11 und mit aktuellster Version ([1.4.3](https://github.com/markocupic/contao-bundle-creator-bundle/tree/1.4.3)) des Bundle-Generators.
Wo genau im Backend kommt es zum Fehler?
Lg M

**Comment by heimseiten** [comment]
Hallo Marko,
danke für das schnelle Feedback. Vielleicht liegt es auch an meinem System. Werde das mal genauer prüfen. Könnte aber ein bisschen dauern. 
LG
