### ISSUE TITLE
Exception on PHP 7.2.19 Sf4.4.40 C4.9.28 post-update-cmd

### ISSUE THREAD

**Issue by cmette** [markocupic/contao-bundle-creator-bundle#17]
hello I've got an exception after install the bundle in a new fresh contao 4.9 environment:

```
Parse error: syntax error, unexpected 'fn' (T_STRING), expecting :: (T_PAAMAYIM_NEKUDOTAYIM) in C:\laragon\www\contao409\vendor\markocupic\contao-bundle-creator-bundle\src\Subscri
ber\Maker\AddStandardTagsMaker.php on line 62
```

at the given location there is a statement that php 7.2 obviously can't execute. a closure with static fn and an arrow statement , if i hack that everything works correctly. Is this an oversight?

**Comment by markocupic** [comment]
https://github.com/markocupic/contao-bundle-creator-bundle/blob/0f6cafbbdaee2036175bc898b309060ddea5caa8/composer.json#L28
