### ISSUE TITLE
Button Vorlage

### ISSUE THREAD

**Issue by skipman** [markocupic/contao-bundle-creator-bundle#18]
Hallo Marco,
Dein bundle-creator ist SUPER!
ABER: Wie bekommt man den Button [Custom Routine starten]? Dieser wird im Fußbereich neben [Speichern], [Speichern und schließen] etc. angezeigt, wenn man einen Datensatz bearbeitet. Das einfache Löschen des Absatzes in der Tabellenbeschreibung (bei mir tl_ff_rank.php) löst eine Fehlermeldung im Backend aus. (ich weiß: Mein Fehler).
Mein Entwicklungsrepository zum nachschauen: [https://github.com/skipman/contao-firefighter-bundle]
![Button_weg](https://user-images.githubusercontent.com/7385395/181636620-81f448e0-06aa-483d-ae5a-ad6ca5dadf2a.png)

**Comment by agonyz** [comment]
Hey @skipman,

die Fehlermeldung erhältst du, weil du versuchst die Klasse bzw. Methode im ```edit - buttons_callback``` zu laden:

```php
'edit'        => array(
        'buttons_callback' => array(
            array('tl_ff_ranks', 'buttonsCallback')
        )
    ),
```

Um den Fehler zu vermeiden, musst du also die Methode aus deiner Klasse entfernen, sofern nicht verwendet und den obigen callback ebenfalls bzw. diesen austauschen.
Du kannst natürlich auch die gesamte Klasse entfernen, sofern du diese nicht an anderer Stelle benötigst.

##

Ich habe dir dazu mal einen Pull Request eröffnet. Diesen kannst du in dein Projekt mergen und dir dann den aktuellen Stand wieder über einen Git Pull holen: https://github.com/skipman/contao-firefighter-bundle/pull/1

Ich kann dir nur mal die Contao Dokumentations ans Herz legen, die ist wirklich Gold wert: https://docs.contao.org/dev/
Bzw. auch das Contao Forum, da der Entwicklerbereich; Super nette Leute und man findet schnell Hilfe: https://community.contao.org/de/

Solltest du noch Fragen dazu haben, kannst du mich auch gerne anschreiben.

##

PS: Das Ticket hier solltest du schließen, da das eigentlich nichts mit der Erweiterung von @markocupic zu tun hat.
