### ISSUE TITLE
Template of Content Element not found (Contao 5.0.9)

### ISSUE THREAD

**Issue by me-mdh** [markocupic/contao-bundle-creator-bundle#19]
Hi Marko,

when creating an extension with a Content Element, after inserting it within an article, I get the following error:

`Tried to list template options for the modern fragment type "content_element/test123" but could not find any template. In case you wanted to use the legacy type "ce_test123", define it explicitly in the "template" property of your controller's service tag/attribute.`

The template file ce_test123.html5 is created within vendor/test123/contao-test-bundle/contao/templates.
Even after trying to add "public $template" or "public $strTemplate" attributes to the class in [bundleDir]/src/Controller/ContentElement/Test123Controller.php it doesn't want to use the legacy template.

Also tried to rename the template to ce_test.html.twig and variations of it, but it just doesn't want to use the template.

Am I missing something? I tried it on a clean install of contao 5.0.9 (see composer.json attached).

Any help is appreciated, thank you for your work and your very nice module!

![screenshot_2023-02-02_00-15-59](https://user-images.githubusercontent.com/124215489/216189187-e63b5895-e5c4-4fba-8bb6-5a4f7beb7b77.png)
![screenshot_2023-02-02_00-15-34](https://user-images.githubusercontent.com/124215489/216189192-bfbdb689-61f3-4443-a227-0a16715947cb.png)
[composer.json.txt](https://github.com/markocupic/contao-bundle-creator-bundle/files/10562853/composer.json.txt)

**Comment by markocupic** [comment]
Hi @me-mdh

If you are running the your content element controller under contao 5, you have to add the name of your legacy template in your class annotation/php8 attribute: 

![image](https://user-images.githubusercontent.com/1525166/216265689-49df9f6e-fa7b-4737-b7b1-7a52dcc933dd.png)

**Comment by me-mdh** [comment]
Thank you very much, also for the very fast response! Worked perfectly.
