### ISSUE TITLE
Danke! Prima!

### ISSUE THREAD

**Issue by cmette** [markocupic/contao-bundle-creator-bundle#3]
Hallo Marko!
Hier mal meine Rückmeldung: Also zuerst einmal vielen Dank für die große Mühe! Bei mir arbeitet dieses Bundle einwandfrei. Ich habe es aber erst seit vorgestern in Betrieb. Eine Anmerkung (bin in Contao 4 aber unerfahren! 3.5 LTS habe ich lange gemacht...) und eine Frage habe ich aber dennoch:
1. Anmerkung: Ich habe zuerst einen Datensatz für ein Bundle angelegt und dabei meinen Vendor-Namen aus Versehen falsch angegeben. Ich hatte das nicht bemerkt, habe die composer.json im root anpassen lassen (Den Repositories-Key erweitern?) und danach habe ich den Datensatz für das Bundle (im creator) aber nochmals editiert und meinen Vendor-Namen korrigiert. Danach habe ich das Bundle wieder erstellen lassen. Mir ist dann aufgefallen, dass der fälschlich eingetragene Verweis in der contao.json (ROOT) nach dem editieren erhalten bleibt. Das Problem (also dieser Fehler **den ich da** gemacht habe) scheint mir zwar softwareseitig sehr schwer handhabbar zu sein, jedoch ist es dennoch kritisch. Der erste falsche Eintrag in der composer.json verhinderte dann das Laden des korrigierten Bundles und das muß man erst mal finden. Das wird gerade dann kompliziert, wenn man den Bundle-Creator **als unerfahrener Contao-4-Entwickler** nutzt (wie ich). Denn der kennt nicht die Zusammenhänge und möchte schnell ein Bundle haben und geht dann davon aus, dass der Generator das schon macht...
2. Frage: Ich möchte nicht unhöflich erscheinen :O) - habe aber eine andere Frage, die mit der Erstellung von Bundles assoziiert ist. **Kennst Du eine Referenz/Site/Doc** etc. die eine **vom Contao-Entwickler-Team standardisierte** Ordnerstruktur beschreibt. Ich beginne mit Contao-4 Bundles zu entwickeln und habe bis jetzt gut und gerne 20 verschiedene Webseiten (einschließlich docs.contao.org) gefunden, die jeweils eigene Strukturen vorschlagen und dabei - wie es mir scheint - das klassische composer-bundle (coposer 4 + 5) und ein contao-bundle (unter vendor) gleich setzten. Das ist meiner jetzigen Kenntnis nach aber nicht korrekt. Wie also sollte eine "richtige" Struktur (sagen wir ab Contao 4.5+) unterhalb von **vendor/my_name/my_bundle** aussehen?

**Zum Schluss aber nochmals vielen Dank für dieses Bundle!**
LG Christian

**Comment by markocupic** [comment]
Ciao Christian

Besten Dank für die Rückmeldung. Ja, das mit der composer.json ist eine crux, da hast du recht. Zu Beginn wollte ich eigentlich die composer.json gar nicht anfassen. Ist aber schon praktisch. Mal schauen, ob mir da noch was einfällt. 

Ordnerstruktur:  Ich glaube, schon, dass ich den offiziellen in der Doku vorgeschlagenen Weg fahre. 


```
vendor
    cmette
        contao-mygenious-plugin-bundle
            src
                ContaoManager
                Controller
                     ContentElement
                     FrontendModule
                DependencyInjection
                Model
                Listener
                ServiceA
                ServiceB
                Resources
                     config
                     contao
                         config
                         dca
                         templates
                         languages
                     public
                     -CmetteContaoMyGeniousPluginBundle.php
            tests
        -composer.json
```

**Comment by cmette** [comment]
Danke! Das ist sehr interessant, was Du da zur Plugin.php geschrieben hast! Ich finde auch: Das Anfassen der composer.json ist nicht so schlimm und überaus praktisch. Ich finde es, so wie es jetzt gelöst ist, sehr gut. Vielleicht würde ein etwas größerer Kommentar an dem Feld >Vendorname< das "Problem" bereits entschärfen. Dann ist der Entwickler informiert, dass der Eintrag in der composer.json möglw. permanent ist, wenn er den Datensatz des Bundles editiert hat.

Mein größtes Problem (als Neuling) ist, dass ich die empfohlene (nicht von Dir sondern die allg. empfohlene) Struktur nicht unbedingt für intuitiv halte. 
1. Wenn es also in einem klassischen Framework Models+Views und Controller gibt, sollte nicht ein Ordner für Views auch zu finden sein? Sollten nicht die (Twig-)Templates dort drin liegen, weil sie View-Komponenten sind? Warum liegen sie unter Ressources?
2. Sind Listener nicht eher Controller?
2. Wohin sollten allgemeine Klassen kommen, wie z.B. MeineHelperClass1.php? 
3. Ist ein CTE im C4 einem Controller ähnlich? bzw. sollte es dort eingeordnet werden?

Diese Fragen sollen bitte keine Kritik darstellen! Mich interessiert eher die Festlegung eines "Standards", den ich selbst (oder Teams) bei der Entwicklung größerer Projekte einhalten könnte...

Ginge das beispielsweise auch so:?

```
vendor/
  vendor_name/
    bundle_name/
      src/
         ContaoManager/
           Plugin.php
         Contao/
           config/
           dca/
         Controller/
           Listener/ oder
           Listener1.php
           ServiceA/
           ServiceB/
         Models/
           Model1.php
           Model2.php
         Views/
         Utils/
           Classes/ oder
           UtilClass1.php
       test/
```
Ich möchte Dir aber nicht die Arbeitszeit klauen :O) Posting einfach ignorieren, wenn Du keine Zeit hast...
Viele Grüße
Christian

**Comment by cmette** [comment]
ach... hab gerade noch gelesen, dass ab 4.8 unterhalb von src/Ressources/contao/ noch languages/ nötig ist ([Quelle](https://contao-academy.de/blog/contao-4-dcaconfig-und-langconfig))

**Comment by markocupic** [comment]
Ja, hier den Überblich zu behalten, wenn man noch nicht vertraut mit Symfony ist, ist wirklich hart. Ich habe damals nicht verstanden, wieso man das gute alte Contao 3.5 hat aufgeben wollen. Inzwischen nach vielen Stunden Netzanalyse und dutzenden von Erweiterungen ist mir aber ganz wohl geworden. Auch finde ich, dass es richtig viel Spass macht mit Contao Erweiterungen zu schreiben. Aber! es ist auch für mich oft immer noch schwierig bei Neuerungen irgendwie Schritt zu halten. 

Ok. Letztlich ist Contao 4 ja nichts anderes als ein Symphony Bundle. Und die Art, wie man Symphony Bundles strukturiert, ist eben so vorgegeben und auch common use.

Controller sind Klassen mit Methoden, welche einen Request verarbeiten, bei ihrer Arbeit weitere Helper dazunehmen (Template-Engines, Models, Utils, etc.) und dann eine Response ausgeben. Das kann in Form von HTML oder bei Ajax-Anfragen auch JSON sein.

Deswegen würde ich sagen, dass Listener und Services da nicht dazugehören. 

In Resources legst du alles ab, was der Composer classautolaoder beim Aufbauen des caches nicht durchsuchen soll. Weil Contao noch nicht komplett refaktoriert ist und an einigen Stellen immer noch Contao 3.5 ist, liegen auch viele dieser "alten" Klassen (auch Controller und viele Library-Classes) immer noch in Resources. Das wird sich aber mittel- und längerfristig ändern. 

Was immer in Resources bleiben wird , sind alle Templates, egal ob twig oder html5. Auch die Contao-typischen dca und language-files werden auch in Zukunft in Rsources/contao residieren.

Aber bitte, alles ohne Gewähr. 

Selbstverständlich bist du frei das jederzeit anders zu machen. ;-)

**Comment by cmette** [comment]
Danke! Wieder was dazugelernt. Habe gerade die beiden Beiträge von Marco Simbürger: Composer verstehen - Teil 5 - Autoloading und Florian Brinkmann: Autoloader mit Composer erstellen - gelesen. Danke für de Tips!
LG
Christian

**Comment by markocupic** [comment]
Tip-top
