### ISSUE TITLE
Frontendmodul Einstellungen

### ISSUE THREAD

**Issue by BugBuster1701** [markocupic/contao-bundle-creator-bundle#4]
Die Beschriftungen an den Feldern passen teilweise nicht zu den Beschreibungen. (mal fett vorgehoben wo ich der Meinung bin, das stimmt was nicht)

Frontendmodul-Kategorie (**snakecase**)*
Geben Sie die Kategorie in **camelcase** an. z.B. **my_custom_modules**

Frontendmodul-**Typ** (snakecase mit "_module" als suffix)*
Geben Sie den **Namen** des Modules in snakecase an. z.B. my_custom_module

**Comment by markocupic** [comment]
Danke dir!
Fixed in 2dc0145.
