### ISSUE TITLE
bundle-generator Version 1.0.40 (30.08.2020, 10:10)

### ISSUE THREAD

**Issue by cmette** [markocupic/contao-bundle-creator-bundle#5]
Hallo Marco,

ich habe eine Rückfrage. Ich habe gerade ein neues Bundle erstellt und möchte nun unter C4.9 am Backend eine eigene Seite aufbauen. Da hat der Generator ja sdchon einen Butten generiert. Leider funktioniert der nicht - oder besser - nicht wie ich es erwartet hätte. Ich nehme mal an, das ist kein Fehler. Willst Du das noch erweitern, so dass es in C4-konformer Weise funktioniert? Der bundle-generator ist ja für C4 gedacht...

1. Also der Button wird mit einer Deklaration in TL_DCA.edit angelegt. Dieser Schlüssel ist laut https://docs.contao.org/dev/reference/dca/ nicht mehr dokumentiert (deprecated?) und ich weiss auch nicht, ob er demnächst entfernt wird. Leider gibt es iim Rahmen der eher mager zu nennenden Contao Dok dazu keine Informationen, warum der Schlüssel nicht mehr dokumentiert ist.
2. Der Key TL_DCA.edit hat seinerseits auch keinen 
`'href' => 'key=my_operation ' `
Eintrag, der für den Aufruf einer Custom-Action am BE nötig wäre. Meiner Kenntnis nach muss zugleich auch noch an dieser Stelle ein
`'class' => 'my_class',`
gesetzt werden, damit der Click-Handler auch die Klasse findet. 

**Ist das alles unter C4.9 noch aktuell oder wie lautet jetzt der Standard?**

Viele Grüße
Theo

**Comment by markocupic** [comment]
Hallo Theo
Ich glaube, der buttons_callback war noch nie dokumentiert. 

Von dessen Abschaffung habe ich noch nichts gehört. 

Wenn ich custom Buttons einbauen, fange ich deren Aufruf jeweils mit einem onload_callback ab.

Siehe:
https://github.com/markocupic/contao-bundle-creator-bundle/blob/2139560be7889de84883c2b920e235716771578e/src/Resources/contao/dca/tl_contao_bundle_creator.php#L378

LG marko
