### ISSUE TITLE
Dein Logo wird automatisch mit verpackt

### ISSUE THREAD

**Issue by math-GH** [markocupic/contao-bundle-creator-bundle#6]
Hallo Marko,

vielen Dank für diese hilfreiche Contao-Bundle.

Ist es gewollt, dass dein Logo als Grafik immer automatisch in den Ressourcne liegt und in die Readme.md eingefügt wird?
Vielleicht könnte eine kleine Checkbox diese Grafik optional auswählen.

**Comment by markocupic** [comment]
Hallo
Ja, es ist gewollt. Da ich das Bundle zu meinem Zweck gebaut habe. Du könntest das aber überschreiben, indem du die entsprechenden Dateien anpasst und im templates Verzeichnis anlegst.

https://github.com/markocupic/contao-bundle-creator-bundle#templates-updatesicher-anpassen
