### ISSUE TITLE
Packagist mag keine Großbuchstaben im Vendornamen

### ISSUE THREAD

**Issue by math-GH** [markocupic/contao-bundle-creator-bundle#7]
Vielleicht kann dieses Problem bereits bei der Eingabe vermieden werden:

![grafik](https://user-images.githubusercontent.com/1645099/102811466-a7564800-43c5-11eb-8170-34393ef888e5.png)

![grafik](https://user-images.githubusercontent.com/1645099/102811489-b0dfb000-43c5-11eb-9929-ac1ebb6f24f2.png)

**Comment by math-GH** [comment]
da habe ich mal nicht aufgepasst: Da ein Linux-System dahinter steckt ist die Groß-Kleinschreibung jeweils ein anderer Ordner.
![grafik](https://user-images.githubusercontent.com/1645099/103133223-89306680-46a9-11eb-81c2-ca5d23db3cf1.png)

**Comment by markocupic** [comment]
fixed in 0fa60aa59d840caf71e08241fa11dcecbae850ce
