### ISSUE TITLE
Installation verursacht Fehler im CM

### ISSUE THREAD

**Issue by skipman** [markocupic/contao-bundle-creator-bundle#8]
Hallo Marco,

nach der Installation des Bundles via CM gibt dieser folgende Fehlermeldung aus:
Parse error on line 1: Deprecated: Not prov ^ Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['
Der Manager ist nicht mehr verfügbar. Das Backend funktioniert noch, aber ohne sichtbare Möglichkeit der Einstellungen, wie in der README gezeigt. 
Während der Installation werden keine neuen Tabellen angelegt, 
Im vendor-Ordner findet sich auch kein Hinweis auf die Extension - kein Ordner "marcocupic"
Der CM zeigt auch kein zusätzliches Paket in der Paketverwaltung an.

Umgebung:
Laragon 4.0.16 mit 
Apache 2.4.35
PHP 7.2.19
mySQL 5.7.24

Contao 4.9.10
Manager v 1.3.3
Symfony 4.4.18

Enabled Bundles:
CmfRoutingBundle | "Symfony\Cmf\Bundle\RoutingBundle\CmfRoutingBundle"
"Contao\CalendarBundle\ContaoCalendarBundle"
"Contao\CommentsBundle\ContaoCommentsBundle"
"Contao\CoreBundle\ContaoCoreBundle"
"Contao\FaqBundle\ContaoFaqBundle"
"Contao\InstallationBundle\ContaoInstallationBundle"
"Contao\ListingBundle\ContaoListingBundle"
"Contao\ManagerBundle\ContaoManagerBundle"
"Contao\NewsBundle\ContaoNewsBundle"
"Contao\NewsletterBundle\ContaoNewsletterBundle"
"Symfony\Bundle\DebugBundle\DebugBundle"
"Doctrine\Bundle\DoctrineBundle\DoctrineBundle"
"FOS\HttpCacheBundle\FOSHttpCacheBundle"
"Symfony\Bundle\FrameworkBundle\FrameworkBundle"
"Knp\Bundle\MenuBundle\KnpMenuBundle"
"Knp\Bundle\TimeBundle\KnpTimeBundle"
"Lexik\Bundle\MaintenanceBundle\LexikMaintenanceBundle"
"Symfony\Bundle\MonologBundle\MonologBundle"
"Nelmio\CorsBundle\NelmioCorsBundle"
"Nelmio\SecurityBundle\NelmioSecurityBundle"
"Scheb\TwoFactorBundle\SchebTwoFactorBundle"
"Symfony\Bundle\SecurityBundle\SecurityBundle"
"Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle"
"Terminal42\ServiceAnnotationBundle\Terminal42ServiceAnnotationBundle"
"Symfony\Bundle\TwigBundle\TwigBundle"
"Symfony\Bundle\WebProfilerBundle\WebProfilerBundle"

**Comment by skipman** [comment]
Online hats funktioniert, prüfe meine lokale Umgebung nochmals. Vielleicht hast Du einen Tipp aufgrund der Fehlermeldung für mich?

Danke Dir!

**Comment by markocupic** [comment]
Hallo 
Ich kann anhand des Postings nicht auf die Ursache des Fehlers schliessen.
Hast du noch mehr Details?
