### ISSUE TITLE
composer.json: Beschreibungstext: Bitte geben Sie nur Buchstaben und Zahlen ein!

### ISSUE THREAD

**Issue by math-GH** [markocupic/contao-bundle-creator-bundle#9]
Im Feld "composer.json: Beschreibungstext" sind die verwendbaren Zeichen sehr stark eingeschränkt.
![grafik](https://user-images.githubusercontent.com/1645099/103455617-edc57400-4cee-11eb-94e7-6e07c2e2b95d.png)

Aktuell sind z.B. folgende Zeichen ausgeschlossen:
Klammern, Doppelpunkt, Ausrufezeichen

Prinzipiell müsste eigentlich nur das doppelte Anführungszeichen (Zoll-Zeichen) ausgeschlossen sein, damit die JSON-Datei nicht defekt ist.

**Comment by markocupic** [comment]
fixed in 946a2d8b013a67447b26c4501b79baa3228106f0
